name: transformer_page_view
description: PageTransformer for flutter
version: 0.1.6
homepage:  https://github.com/yinxing29/transformer_page_view_copy

environment:
  sdk: ">=2.12.0 <3.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
